import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {TopBar} from "../components/TopBar";
import { Sidebar } from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full`}
      >
        {/* Background Image */}
        <div className="fixed inset-0 -z-10 overflow-hidden">
          <Image
            src="/chatty_bg.jpg"
            alt="Background"
            fill
            style={{ objectFit: 'cover' }}
            placeholder="blur"
            blurDataURL="/your-background-blur.jpg"
            className="w-full h-full object-cover filter blur-xs scale-110"
            priority
          />
        </div>

        {/* Main Layout Container */}
        <div className="flex flex-col gap-12 h-full w-full p-4 ">
          {/* TopBar - Full Width */}
          <div className="h-16 w-full flex-shrink-0">
            <TopBar />
          </div>

          {/* Content Area - Sidebar + Main Content */}
          <div className="flex flex-1 overflow-hidden gap-12">
            {/* Sidebar - 1/3 width */}
            <div className="w-1/3 flex-shrink-0">
              <Sidebar
                friends={[
                  {
                    name: 'Jay123',
                    id: '22',
                    isOnline: true,
                    latestChat: "Bro the baddies were not letting me hit last night it was so fkn annoying"
                  },
                  {
                    name: 'Nigg00',
                    id: '3',
                    isOnline: false,
                    latestChat: "Bro the baddies were not letting me hit last night it was so fkn annoying"
                  }
                ]}
              />
            </div>

            {/* Main Content - Remaining width */}
            <div className="flex-1 overflow-auto rounded-2xl border-[2px] border-white bg-[rgba(255,255,255,0.5)]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}